#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
#
Name     : hiredis-c
Version  : 1.2.0
Release  : 6
URL      : https://github.com/redis/hiredis/archive/v1.2.0/hiredis-1.2.0.tar.gz
Source0  : https://github.com/redis/hiredis/archive/v1.2.0/hiredis-1.2.0.tar.gz
Summary  : SSL Support for hiredis.
Group    : Development/Tools
License  : BSD-3-Clause
Requires: hiredis-c-lib = %{version}-%{release}
Requires: hiredis-c-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : openssl-dev
BuildRequires : pkgconfig(glib-2.0)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
[![Build Status](https://github.com/redis/hiredis/actions/workflows/build.yml/badge.svg)](https://github.com/redis/hiredis/actions/workflows/build.yml)

%package dev
Summary: dev components for the hiredis-c package.
Group: Development
Requires: hiredis-c-lib = %{version}-%{release}
Provides: hiredis-c-devel = %{version}-%{release}
Requires: hiredis-c = %{version}-%{release}

%description dev
dev components for the hiredis-c package.


%package lib
Summary: lib components for the hiredis-c package.
Group: Libraries
Requires: hiredis-c-license = %{version}-%{release}

%description lib
lib components for the hiredis-c package.


%package license
Summary: license components for the hiredis-c package.
Group: Default

%description license
license components for the hiredis-c package.


%prep
%setup -q -n hiredis-1.2.0
cd %{_builddir}/hiredis-1.2.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1692217928
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FCFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export CXXFLAGS="$CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
%cmake ..
make  %{?_smp_mflags}
popd
mkdir -p clr-build-avx2
pushd clr-build-avx2
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -Wl,-z,x86-64-v3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd -march=x86-64-v3 "
export FCFLAGS="$FFLAGS -O3 -Wl,-z,x86-64-v3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd -march=x86-64-v3 "
export FFLAGS="$FFLAGS -O3 -Wl,-z,x86-64-v3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd -march=x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -O3 -Wl,-z,x86-64-v3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd -march=x86-64-v3 "
export CFLAGS="$CFLAGS -march=x86-64-v3 -m64 -Wl,-z,x86-64-v3"
export CXXFLAGS="$CXXFLAGS -march=x86-64-v3 -m64 -Wl,-z,x86-64-v3"
export FFLAGS="$FFLAGS -march=x86-64-v3 -m64 -Wl,-z,x86-64-v3"
export FCFLAGS="$FCFLAGS -march=x86-64-v3 -m64 -Wl,-z,x86-64-v3"
%cmake ..
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1692217928
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/hiredis-c
cp %{_builddir}/hiredis-%{version}/COPYING %{buildroot}/usr/share/package-licenses/hiredis-c/e9c1298de98016808910005a33de3a5f25dce05e || :
pushd clr-build-avx2
%make_install_v3  || :
popd
pushd clr-build
%make_install
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/build/native/hiredis.targets

%files dev
%defattr(-,root,root,-)
/usr/include/hiredis/adapters/ae.h
/usr/include/hiredis/adapters/glib.h
/usr/include/hiredis/adapters/ivykis.h
/usr/include/hiredis/adapters/libev.h
/usr/include/hiredis/adapters/libevent.h
/usr/include/hiredis/adapters/libhv.h
/usr/include/hiredis/adapters/libsdevent.h
/usr/include/hiredis/adapters/libuv.h
/usr/include/hiredis/adapters/macosx.h
/usr/include/hiredis/adapters/poll.h
/usr/include/hiredis/adapters/qt.h
/usr/include/hiredis/adapters/redismoduleapi.h
/usr/include/hiredis/alloc.h
/usr/include/hiredis/async.h
/usr/include/hiredis/hiredis.h
/usr/include/hiredis/read.h
/usr/include/hiredis/sds.h
/usr/include/hiredis/sockcompat.h
/usr/lib64/cmake/hiredis/hiredis-config-version.cmake
/usr/lib64/cmake/hiredis/hiredis-config.cmake
/usr/lib64/cmake/hiredis/hiredis-targets-relwithdebinfo.cmake
/usr/lib64/cmake/hiredis/hiredis-targets.cmake
/usr/lib64/libhiredis.so
/usr/lib64/pkgconfig/hiredis.pc

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libhiredis.so.1.1.0
/usr/lib64/libhiredis.so.1.1.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/hiredis-c/e9c1298de98016808910005a33de3a5f25dce05e
